### ISSUE TITLE
Can't submit a proposal that's not been accepted/rejected yet

### ISSUE THREAD

**Issue by andrew** [nodunayo/speakerline#22]
Not sure if this is by design, but a "submission" requires choosing one of approved/rejected, but I only put the proposal in today so it's neither.

Is it better to:

- Not add until it's been approved/rejected by the conf
- Add a third "submitted" or "pending" option
- something else I didn't think of

**Comment by nodunayo** [comment]
The original design of this was intentional, but I was expecting it to be brought up for discussion.

I think the most value comes from being able to see the outcome of submissions, rather than a list of places that the proposal has been submitted to.

I have a concern that if you allow a pending option then people will input their proposal and add a list of submissions, but then won't come back to update the outcome of submissions.

On the other hand, I don't want to prevent people from inputting proposals that haven't been accepted or rejected yet (which is how it currently works).

Now I'm thinking about it, maybe it is useful to see that a proposal has indeed been submitted to places, rather than just something the speaker wrote up and didn't put out there for somebody to see.

In any case, a list of 'Pending' submissions could be a prompt to somebody to ping the speaker or update the record themselves.

Thoughts?

**Comment by jemagee** [comment]
I was thinking there could be someway to automate it?  I don’t submit talks nor have time to go to these things but do they have ‘fixed dates’ when they announce their slate of talks?  If so you could have an automated notification to someone (the poster them selves? ) on that date that any pending talks for the given talk need to be updated. (Plus, I’m sure there are lists provide either through XML CSV or some other format that you might be able to use to automatically update it - find all the pending talks for a given event, if they’re not on the list they were rejected, if they are it’s accepted’)

Just some thoughts (i’m often drawn towards thinking of ways to make things automatic to limit the burden on people doing things if they don’t have to)

**Comment by nodunayo** [comment]
Hi John,

Sorry it's taken me so long to reply to this.

Generally, I love the idea of having some automatic way of working out when a decision should have been made on a talk or not. At the very latest, decisions about an event will have been made by the day of the event! 

Then there can be some form of notification, either to the poster (you'd then need poster information) or on the website about proposals that need updating.

I think that this is rather complicated for this stage of the project though. Let's see how others use the site as it stands and go from there, I reckon.

**Comment by nodunayo** [comment]
Dealt with in: https://github.com/nodunayo/speakerline/pull/56

**Comment by andrew** [comment]
🎉
