### ISSUE TITLE
Add a contributing guide

### ISSUE THREAD

**Issue by nodunayo** [nodunayo/speakerline#5]
This project is (currently) a very basic Rails app, perfect for newer developers to get stuck into open source with.

24 Pull Requests has a very helpful contributing guide and it'd be great if this project had something similar: https://github.com/24pullrequests/24pullrequests/blob/master/CONTRIBUTING.md.

**Comment by alicetragedy** [comment]
I'd love to help out with this (I originally helped with the 24 Pull Requests guide) 🙈 
I could come up with a basic list of what might be helpful to know as a future contributor, and then draft a first contributing guide?

**Comment by nodunayo** [comment]
@alicetragedy Yes, you did! I remember our thread on it December past.

That would be amazing! Thanks a lot. :-)

**Comment by alicetragedy** [comment]
Sorry for dropping the ball on this one; I am still interested in working on it, but looking at the way things are going for me right now, I probably won't get to it until mid-May. If anyone else is interested in working on it in the meanwhile, feel free to do so — don't want to sit on this issue :) Otherwise I'll check back in a month or so!

**Comment by nodunayo** [comment]
Hi Laura!

No worries. Sorry for the slow response on my end; I've been alone.

Yes, there's not rush on this at all. Hopefully in a month or so we've moved on a bit and there'll be more issues for people to get stuck into!

**Comment by nodunayo** [comment]
Resolved in https://github.com/nodunayo/speakerline/commit/e52782cb9e758588f3507cd183e73da219e2bc04!  🎉

Wanted to get one in before @24pullrequests kicks in.
